### ISSUE TITLE
Class Based View - Issue

### ISSUE THREAD

**Issue by shaileshbc** [buckyroberts/Viberr#4]
I have changed your code for Class Based View.
after Login into the music app, it shows list of albums, but
if you press Album in a menu, it does not show any album.
you can find my code at https://github.com/shaileshbc/viberr
login user into the app as 
username: sbc
password: sbc
can you please find out what is wrong with the code, as i a new to django.
regards
Shaileshbc

**Comment by shaileshbc** [comment]
It has been resolved.
Thanks
Shailesh

**Comment by IHackPy** [comment]
your code is looking good!!!!!!!!!!!!!!
